config/routes.rb
Rails.application.routes.draw do
  resources :comensales
  resources :turnos
  resources :boos
  resources :reloj
  resources :servicio
  devise_for :users
  devise_for :models
  post 'reloj' => 'reloj#action'
  #root to: 'sign_up#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => 'servicio#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boo.rb
class Boo < ApplicationRecord
end

app/models/comensale.rb
class Comensale < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/turno.rb
class Turno < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/boos_controller.rb
class BoosController < ApplicationController
  before_action :set_boo, only: [:show, :edit, :update, :destroy]

  # GET /boos
  # GET /boos.json
  def index
    @boos = Boo.all
  end

  # GET /boos/1
  # GET /boos/1.json
  def show
  end

  # GET /boos/new
  def new
    @boo = Boo.new
  end

  # GET /boos/1/edit
  def edit
  end

  # POST /boos
  # POST /boos.json
  def create
    @boo = Boo.new(boo_params)

    respond_to do |format|
      if @boo.save
        format.html { redirect_to @boo, notice: 'Boo was successfully created.' }
        format.json { render :show, status: :created, location: @boo }
      else
        format.html { render :new }
        format.json { render json: @boo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boos/1
  # PATCH/PUT /boos/1.json
  def update
    respond_to do |format|
      if @boo.update(boo_params)
        format.html { redirect_to @boo, notice: 'Boo was successfully updated.' }
        format.json { render :show, status: :ok, location: @boo }
      else
        format.html { render :edit }
        format.json { render json: @boo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boos/1
  # DELETE /boos/1.json
  def destroy
    @boo.destroy
    respond_to do |format|
      format.html { redirect_to boos_url, notice: 'Boo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boo
      @boo = Boo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boo_params
      params.require(:boo).permit(:hola)
    end
end

app/controllers/comensales_controller.rb
class ComensalesController < ApplicationController
  before_action :set_comensale, only: [:show, :edit, :update, :destroy]

  # GET /comensales
  # GET /comensales.json
  def index
    @comensales = Comensale.all
  end

  # GET /comensales/1
  # GET /comensales/1.json
  def show
  end

  # GET /comensales/new
  def new
    @comensale = Comensale.new
  end

  # GET /comensales/1/edit
  def edit
  end

  # POST /comensales
  # POST /comensales.json
  def create
    @comensale = Comensale.new(comensale_params)

    respond_to do |format|
      if @comensale.save
        format.html { redirect_to @comensale, notice: 'Comensale was successfully created.' }
        format.json { render :show, status: :created, location: @comensale }
      else
        format.html { render :new }
        format.json { render json: @comensale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comensales/1
  # PATCH/PUT /comensales/1.json
  def update
    respond_to do |format|
      if @comensale.update(comensale_params)
        format.html { redirect_to @comensale, notice: 'Comensale was successfully updated.' }
        format.json { render :show, status: :ok, location: @comensale }
      else
        format.html { render :edit }
        format.json { render json: @comensale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comensales/1
  # DELETE /comensales/1.json
  def destroy
    @comensale.destroy
    respond_to do |format|
      format.html { redirect_to comensales_url, notice: 'Comensale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comensale
      @comensale = Comensale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comensale_params
      params.require(:comensale).permit(:nombre, :codigo)
    end
end

app/controllers/reloj_controller.rb
class RelojController < ApplicationController
      before_action :set_comensale, only: [:show, :edit, :update, :destroy]
    users = Comensale.all
    david = Comensale.first
    
    def create
    end

    def action
        @login = params[:codigo]
        @dav = Comensale.find_by(codigo: @login)
        render :text => "No Data" and return
        
    end 
end

app/controllers/servicio_controller.rb
class ServicioController < ApplicationController
    def create
    end
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: [:show, :edit, :update, :destroy]

  # GET /turnos
  # GET /turnos.json
  def index
    @turnos = Turno.all
  end

  # GET /turnos/1
  # GET /turnos/1.json
  def show
  end

  # GET /turnos/new
  def new
    @turno = Turno.new
  end

  # GET /turnos/1/edit
  def edit
  end

  # POST /turnos
  # POST /turnos.json
  def create
    @turno = Turno.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno was successfully created.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnos/1
  # PATCH/PUT /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to @turno, notice: 'Turno was successfully updated.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1
  # DELETE /turnos/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turno_params
      params.require(:turno).permit(:codigoturno, :horas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boos_helper.rb
module BoosHelper
end

app/helpers/comensales_helper.rb
module ComensalesHelper
end

app/helpers/reloj_helper.rb
module RelojHelper
end

app/helpers/servicio_helper.rb
module ServicioHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/boos/_form.html.erb
<%= form_for(boo) do |f| %>
  <% if boo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boo.errors.count, "error") %> prohibited this boo from being saved:</h2>

      <ul>
      <% boo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hola %>
    <%= f.text_field :hola %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boos/edit.html.erb
<h1>Editing Boo</h1>

<%= render 'form', boo: @boo %>

<%= link_to 'Show', @boo %> |
<%= link_to 'Back', boos_path %>

app/views/boos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boos</h1>

<table>
  <thead>
    <tr>
      <th>Hola</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boos.each do |boo| %>
      <tr>
        <td><%= boo.hola %></td>
        <td><%= link_to 'Show', boo %></td>
        <td><%= link_to 'Edit', edit_boo_path(boo) %></td>
        <td><%= link_to 'Destroy', boo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<%= link_to 'New Boo', new_boo_path %>

app/views/boos/new.html.erb
<h1>New Boo</h1>

<%= render 'form', boo: @boo %>

<%= link_to 'Back', boos_path %>

app/views/boos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hola:</strong>
  <%= @boo.hola %>
</p>

<%= link_to 'Edit', edit_boo_path(@boo) %> |
<%= link_to 'Back', boos_path %>

app/views/comensales/_form.html.erb
<%= form_for(comensale) do |f| %>
  <% if comensale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comensale.errors.count, "error") %> prohibited this comensale from being saved:</h2>

      <ul>
      <% comensale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :codigo %>
    <%= f.number_field :codigo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comensales/edit.html.erb
<h1>Editing Comensale</h1>

<%= render 'form', comensale: @comensale %>

<%= link_to 'Show', @comensale %> |
<%= link_to 'Back', comensales_path %>

app/views/comensales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comensales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comensales.each do |comensale| %>
      <tr>
        <td><%= comensale.nombre %></td>
        <td><%= comensale.codigo %></td>
        <td><%= link_to 'Show', comensale %></td>
        <td><%= link_to 'Edit', edit_comensale_path(comensale) %></td>
        <td><%= link_to 'Destroy', comensale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comensale', new_comensale_path %>

app/views/comensales/new.html.erb
<h1>New Comensale</h1>

<%= render 'form', comensale: @comensale %>

<%= link_to 'Back', comensales_path %>

app/views/comensales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comensale.nombre %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @comensale.codigo %>
</p>

<%= link_to 'Edit', edit_comensale_path(@comensale) %> |
<%= link_to 'Back', comensales_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comedor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Hospital Viedma</a>
        </div>
      </nav>
    <%= yield %>
    <br></br>
    <%= button_to("Cerrar sesion", destroy_user_session_path, :method => :delete) %>
  </body>
</html>

app/views/reloj/new.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script>
    function ActualizarHora(){
    var fecha = new Date();
    var segundos = fecha.getSeconds();
    var minutos = fecha.getMinutes();
    var horas = fecha.getHours();
 
    var elementoHoras = document.getElementById("pHoras");
    var elementoMinutos = document.getElementById("pMinutos");
    var elementoSegundos = document.getElementById("pSegundos");
    var pSaludo = document.getElementById("contSaludo");
 
    elementoHoras.textContent = horas;
    elementoMinutos.textContent = minutos;
    elementoSegundos.textContent = segundos;
    
 
    if (horas >= 8 && minutos >= 1 && horas < 12) {
        pSaludo.textContent = "buenos días";
    }
    if (horas >= 12 && minutos >= 1 && horas < 19) {
        pSaludo.textContent = "buenas tardes";
    }
    if (horas >= 19 && minutos >= 1) {
        pSaludo.textContent = "buenas noches";
    }
}
 
setInterval(ActualizarHora,1000);
    </script>
</head>
<body>

    <h2><section id="contSaludo"></section></h2>
    <div class="row">
    <section id="contReloj">
      <div class="col s2"><p>Horas</p><h2 id="pHoras"></h2></div>
      <div class="col s2"><h2>:</h2></div>
      <div class="col s2"><p>Minutos</p><h2 id="pMinutos"></h2></div>
      <div class="col s2"><h2>:</h2></div>
      <div class="col s2"><p>Segundos</p><h2 id="pSegundos"></h2></div>
      </section>
    </div>
    
    


<%= form_tag("/reloj", method: "post") do %>
  <%= label_tag(:codigo, "Ingrgese su codigo:") %>
  <%= text_field_tag(:codigo) %>
  <br>
  
  <br>
  <%= submit_tag("Recoger") %>
<% end %>

    </body>
</html>

app/views/servicio/new.html.erb
   
<h2>Elija un Servicio </h2>
<%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <div class="row">
      <div class="col s3">
      
      <div class="card">
            <div class="card-image">
              <%=image_tag("planilla.png", height: '320', width: '320')%>
              <span class="card-title">Comeensales</span>
            </div>
            <div class="card-content">
              <p>lista de los comensales</p>
            </div>
            <div class="card-action">
              <p> <%= link_to 'Plantilla de Comensales', comensales_path %></p>
            </div>
          </div>
      </div>
      <div class="col s3">
            <div class="card">
            <div class="card-image">
              <%=image_tag("images.png", height: '320', width: '320')%>
              <span class="card-title">Turno</span>
            </div>
            <div class="card-content">
              <p>lista de los Turnos</p>
            </div>
            <div class="card-action">
              <p> <%= link_to 'Turno', turnos_path %></p>
            </div>
          </div>
      </div>
      <div class="col s3">
        <div class="card">
                <div class="card-image">
                <%=image_tag("acceso.png", height: '320', width: '320')%>
                <span class="card-title">Control de Acceso</span>
                </div>
                <div class="card-content">
                <p>Control de Acceso de Comensales</p>
                </div>
                <div class="card-action">
                <p> <%= link_to 'Control de Acceso', new_reloj_path  %></p>
                </div>
        </div>
      </div>
    <div class="col s3">
        <div class="card">
                <div class="card-image">
                <%=image_tag("user.png", height: '320', width: '320')%>
                <span class="card-title">Crear nuevo Usuario</span>
                </div>
                <div class="card-content">
                <p>Crear nuevo Usuario</p>
                </div>
                <div class="card-action">
                <p> <%= link_to 'Crear nuevo Usuario', user_session_path, :method => :new  %></p>
                </div>
        </div>
      </div>
    </div>
    <div class="fixed-action-btn">

  </div>

app/views/turnos/_form.html.erb
<%= form_for(turno) do |f| %>
  <% if turno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turno.errors.count, "error") %> prohibited this turno from being saved:</h2>

      <ul>
      <% turno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigoturno %>
    <%= f.number_field :codigoturno %>
  </div>

  <div class="field">
    <%= f.label :horas %>
    <%= f.number_field :horas %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turnos/edit.html.erb
<h1>Editing Turno</h1>

<%= render 'form', turno: @turno %>

<%= link_to 'Show', @turno %> |
<%= link_to 'Back', turnos_path %>

app/views/turnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turnos</h1>

<table>
  <thead>
    <tr>
      <th>Codigoturno</th>
      <th>Horas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnos.each do |turno| %>
      <tr>
        <td><%= turno.codigoturno %></td>
        <td><%= turno.horas %></td>
        <td><%= link_to 'Show', turno %></td>
        <td><%= link_to 'Edit', edit_turno_path(turno) %></td>
        <td><%= link_to 'Destroy', turno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turno', new_turno_path %>

app/views/turnos/new.html.erb
<h1>New Turno</h1>

<%= render 'form', turno: @turno %>

<%= link_to 'Back', turnos_path %>

app/views/turnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigoturno:</strong>
  <%= @turno.codigoturno %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @turno.horas %>
</p>

<%= link_to 'Edit', edit_turno_path(@turno) %> |
<%= link_to 'Back', turnos_path %>